# Generated by Django 4.1.1 on 2022-09-25 17:09

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1500)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['created'])),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=1500)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='media/course/%Y/%m/%d/')),
                ('video_intro', models.CharField(default='', max_length=1500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': 'Khóa học',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Type_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['created'])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục khóa học',
                'verbose_name_plural': 'Danh mục khóa học',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['created'])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='course.course')),
            ],
            options={
                'verbose_name': 'Chủ đề',
                'verbose_name_plural': 'Chủ đề',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='type_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.type_course'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=['created'])),
                ('video', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='course.course')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course.topic')),
            ],
            options={
                'verbose_name': 'Bài học',
                'verbose_name_plural': 'Bài học',
                'ordering': ('-created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.AlterIndexTogether(
            name='course',
            index_together={('id', 'slug')},
        ),
    ]
