# Generated by Django 4.1.1 on 2022-09-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
    ]
