# Generated by Django 4.1.1 on 2022-09-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(max_length=15000),
        ),
    ]
