# Generated by Django 4.1.1 on 2022-10-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_lesson_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.TextField(),
        ),
    ]
