# Generated by Django 4.1.1 on 2022-09-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_intro',
            field=models.CharField(default='', max_length=150),
        ),
    ]
