# Generated by Django 4.1.1 on 2022-09-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_video_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=150000),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=1500),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_intro',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
