# Generated by Django 4.1.1 on 2022-10-08 19:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=1500, verbose_name='Tên khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=1500, verbose_name='Loại khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_intro',
            field=models.TextField(default='', max_length=1500, verbose_name='Video giới thiệu'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên leeson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='time',
            field=models.CharField(max_length=150, verbose_name='Thời gian'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.TextField(verbose_name='Link video'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên topic'),
        ),
        migrations.AlterField(
            model_name='type_course',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên loại khóa học'),
        ),
    ]
