# Generated by Django 4.1.1 on 2022-09-24 19:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
