# Generated by Django 4.1.1 on 2022-10-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_description_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0, verbose_name='Giá khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất'),
        ),
        migrations.AlterField(
            model_name='type_course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
    ]
