# Generated by Django 4.1.1 on 2022-12-12 03:43

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tên tin tức')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['created'])),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Mô tả')),
                ('image', models.ImageField(upload_to='media/course/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Tin tức',
                'verbose_name_plural': 'Tin tức',
            },
        ),
    ]
