# Generated by Django 4.1.1 on 2023-01-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vnp_TxnRef', models.CharField(max_length=150, verbose_name='Mã đơn hàng')),
                ('vnp_Amount', models.CharField(max_length=150, verbose_name='Tổng đơn hàng')),
                ('vnp_BankCode', models.CharField(max_length=150, verbose_name='Ngân hàng')),
                ('vnp_BankTranNo', models.CharField(max_length=150, verbose_name='Mã giao dịch')),
                ('vnp_CardType', models.CharField(max_length=150, verbose_name='Loại thanh toán')),
                ('vnp_OrderInfo', models.CharField(max_length=150, verbose_name='Thông tin thanh toán')),
                ('vnp_PayDate', models.CharField(max_length=150, verbose_name='Ngày thanh toán')),
                ('vnp_ResponseCode', models.CharField(max_length=150, verbose_name='Mã Trả về')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất')),
            ],
            options={
                'verbose_name': 'Danh sách hóa đơn thanh toán',
                'verbose_name_plural': 'Danh sách hóa đơn thanh toán',
            },
        ),
    ]
