# Generated by Django 4.1.1 on 2023-01-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnpay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vnp_PayDate',
            field=models.DateTimeField(max_length=150, verbose_name='Ngày thanh toán'),
        ),
    ]
