# Generated by Django 4.1.1 on 2022-11-23 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0007_type_course_updated_alter_course_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('status', models.CharField(choices=[('0', 'Chưa thanh toán'), ('1', 'Đã thanh toán')], default='0', max_length=10, verbose_name='Trạng thái')),
                ('total_price', models.FloatField(verbose_name='Tổng tiền')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Ngày chỉnh sửa gần nhất')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150)),
                ('course_slug', models.CharField(max_length=150)),
                ('course_price', models.FloatField(blank=True, null=True)),
                ('course_img', models.CharField(max_length=150)),
                ('total', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered', to='course.course')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
